### ISSUE TITLE
Add lineBreak Options

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss-selector-matches#1]
## lineBreak(default: true)

input: 

``` css
p:matches(:first-child, .special) {
  color: red;
}
```

You will get:

``` css
p:first-child,
p.special {
  color: red;
}
```

See also: [postcss-custom-selectors](https://github.com/postcss/postcss-custom-selectors#options)
