### ISSUE TITLE
2.0.2 and 2.0.3 produce garbled output when used with postcss-custom-selectors

### ISSUE THREAD

**Issue by rgrove** [postcss/postcss-selector-matches#10]
PR #8, which was released in 2.0.2, seems to break [postcss-custom-selectors](https://github.com/postcss/postcss-custom-selectors/).

Here's a simple repro:
## Input

``` css
@custom-selector :--link a, a:active, a:visited;

:--link.foo,
.foo {
  color: green;
}
```
## Expected Output

This is what you get with postcss-selector-matches <= 2.0.1.

``` css
a.foo,
a:active.foo,
a:visited.foo,
.foo {
  color: green;
}
```
## Actual Output

This is what you get starting with postcss-selector-matches 2.0.2. Note the garbled `o.fo` classname.

``` css
a.foo,
a:active.foo,
a:visited.foo,
o.fo {
  color: green;
}
```
