### ISSUE TITLE
Not support :nth-child() selector

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss-selector-matches#2]
Input:

```
.foo:matches(:nth-child(-n+2), .bar) {
  color: red;
}
```

Output:

``` css
.foo:nth-child(-n+2, .bar) {
  color: red;
}
```

The right output is:

``` css
.foo:nth-child(-n+2), .foo.bar {
  color: red;
}
```
