### ISSUE TITLE
Strange output with custom selector and :matches()

### ISSUE THREAD

**Issue by ntharim** [postcss/postcss-selector-matches#3]
An example:

``` css
@custom-selector :--buttons button, .button;

 :--buttons:matches(:hover, :active) {
  display: none;
 }
```

`postcss-custom-selectors` would generate:

``` css
button:matches(:hover, :active),
.button:matches(:hover, :active) {
  display: none;
 }
```

From this, `postcss-selector-matches` would generate:

``` css
button:hover, .button:hover, button:active, .button:hover, button:hover, .button:active, button:active, .button:active {
  display: none;
}
```

Shouldn't the output be close to something like this instead?

``` css
button:hover, button:active, .button:hover, .button:active {
  display: none;
}
```

This gets worse if you're trying to match at lot of things like `:matches(:hover, :active, :focus, .active)`.
