### ISSUE TITLE
matches() does not work with pseudo-elements

### ISSUE THREAD

**Issue by topaxi** [postcss/postcss-selector-matches#4]
Input:

``` css
.foo:matches(:hover, :focus)::before {
  color: red;
}
```

Expected:

``` css
.foo:hover::before, .foo:focus::before {
  color: red;
}
```

Actual:

``` css
.foo:hover ::before, .foo:focus ::before {
  color: red;
}
```

This just stopped working, I'm not sure which version update caused this (using cssnext, happens on http://cssnext.io/playground/ too).
