### ISSUE TITLE
:matches(element)

### ISSUE THREAD

**Issue by stevenvachon** [postcss/postcss-selector-matches#7]
``` css
.class {
  &:matches(element) {
    property: value;
  }
}
```

produces:

``` css
.classelement {
  property: value;
}
```

when it _should_ produce:

``` css
element.class {
  property: value;
}
```

Tied to [postcss-cssnext#287](https://github.com/MoOx/postcss-cssnext/issues/287#issuecomment-226379100).

**Comment by MoOx** [comment]
PR welcome :)

**Comment by stevenvachon** [comment]
I haven't worked with PostCSS under the hood, so I probably won't have the time to help much. Have even been having difficulty finding time for my own projects lately.

**Comment by MoOx** [comment]
> Have even been having difficulty finding time for my own projects lately.

My life :D

**Comment by delorge** [comment]
there is a testcase for this one: 
```
transform("p:matches(a, span) {}"),
    "pa, pspan {}",
```

maybe transforming goes this way because 
`
.class {
  &:matches(element) {
    property: value;
  }
}`

will be tranformed to `class:matches(element)`?

**Comment by Swizz** [comment]
Hi,

I do not know is the right way to ask this in this issue or this repository.

Howether, I started to put my interest on the cssnext features. And [the matches specs](https://drafts.csswg.org/selectors-4/#matches) is unclear.

I quickly understood that `:matches()` is used to avoid the overuse of

``` css
p.foo, p.bar, p.baz, p.[...] {}

/* reduced to */
p:matches(.foo, .bar, .baz) {}
```

But.. is it possible to use `:matches()` in this scenario ?

``` css
form > *:matches(button, a.button, input[type=button])

/* or */
form  matches(> button, > a.button, > input[type=button])

/* instead of */
form > button,
form > a.button,
form > input[type=button])
{}
```

Cheer,

**Comment by MoOx** [comment]
Closed by #8

**Comment by stevenvachon** [comment]
@MoOx @yordis 
I'm still experiencing issues with this, but with a more specific case now:

``` css
.namespace {
  &:not(.classA, .classB) {
    &:matches(element) {
      property: value;
    }
  }
}
```

is resulting in:

``` css
.namespace:not(.classA):not(.classB)element {
  property: value;
}
```

Meanwhile, this:

``` css
.namespace {
  &:not(.classA) {
    &:matches(element) {
      property: value;
    }
  }
}
```

compiles correctly into:

``` css
element.namespace:not(.classA) {
  property: value;
}
```

Here's another test case:

``` css
.list {
  &:matches(ol, ul) {
    property: value;
    li {
      property: value;
    }
  }

  &:matches(ol) {
    property: value;
    li {
      property: value;
    }
  }
}
```

**Comment by MoOx** [comment]
Feel free to make a PR to fix this :)

**Comment by stevenvachon** [comment]
It's actually even more fuxed than I'd thought. My compiled CSS has `:matches(...)` in it.

**Comment by clarfonthey** [comment]
I also think that cases like `p:matches(a)` should simply be removed rather than concatenating like the README states.

**Comment by SassNinja** [comment]
I'm also facing an issue with a (quite simple) element selector.

```css
.foo > .bar:matches(a) {
  color: red;
}
```

compiles to 

```css
.foo > .bara {
  color: red;
}
```

instead of

```css
.foo > a.bar {
  color: red;
}
```
